<a href="https://colab.research.google.com/github/NaraineSurya/Tutorials/blob/master/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **Basics**

In [3]:
a = np.array([1, 3, 5], dtype = 'int32')
print(a)

[1 3 5]


In [4]:
b = np.array([[1.4, 3.6, 4.7], [5.7, 6.4, 7.8]])
print(b)

[[1.4 3.6 4.7]
 [5.7 6.4 7.8]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get Data Type
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
# Get Size in bytes
a.itemsize
print(b.itemsize)

8


In [11]:
# Get Total size
print(a.nbytes)
print(b.nbytes)

12
48


In [12]:
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
# Get an element
a[1, 0]

7

In [14]:
# Get a row
a[0, :]

array([1, 2, 3, 4, 5, 6])

In [15]:
# Get a column
a[:, 1]

array([2, 8])

In [16]:
# Get values from interval
a[0, 0:6:2]

array([1, 3, 5])

In [17]:
# Change value in the numpy array
a[0, 5] = 20
a

array([[ 1,  2,  3,  4,  5, 20],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
# Update entire row
a[0, :] = 55
a

array([[55, 55, 55, 55, 55, 55],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
# Update entire column
a[:, 4] = 66
a

array([[55, 55, 55, 55, 66, 55],
       [ 7,  8,  9, 10, 66, 12]])

In [20]:
# 3D in numpy
b = np.array([[[1,2,9], [3,4,10]], [[5,6,11], [7,8,12]]])
print(b)
print(b.shape)

[[[ 1  2  9]
  [ 3  4 10]]

 [[ 5  6 11]
  [ 7  8 12]]]
(2, 2, 3)


In [21]:
# Get a specified element

b[0][1][2]

10

In [22]:
# Get a row from 3D array
b[1][1]

array([ 7,  8, 12])

In [23]:
# Get a column from 3D array
b[:, :, 1]


array([[2, 4],
       [6, 8]])

# **Different Initialization in Numpy Arrays**

In [24]:
# Zero arrays
a = np.zeros((2,5), dtype= "int32")
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [25]:
# Arrays of value one
b = np.ones((3,6), dtype="int64")
b

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [26]:
# Fill the array with given value

a = np.full((2,4), 100, dtype='int32')
a

array([[100, 100, 100, 100],
       [100, 100, 100, 100]], dtype=int32)

In [27]:
# Random Decimal Numbers

np.random.rand(3,2)

array([[0.79968836, 0.43612627],
       [0.57926627, 0.070494  ],
       [0.6874012 , 0.68245958]])

In [28]:
# Random Integers

np.random.randint(1,7, size=(3,7))

array([[1, 6, 3, 5, 3, 6, 1],
       [5, 2, 3, 4, 5, 5, 2],
       [5, 5, 1, 2, 2, 1, 3]])

In [29]:
# Random Numbers for existing shape
np.random.random_sample(a.shape)

array([[0.11748569, 0.07215982, 0.04961818, 0.38934858],
       [0.60015242, 0.62005953, 0.20736673, 0.74393107]])

In [30]:
# Identity Matrix is a Square Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a = np.ones((5,5), dtype='int32')
z = np.zeros((3,3), dtype= 'int32')
print(a)
print(z)

z[1, 1] = 9
a[1:4, 1:4] = z
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# **Copying Numpy Arrays**

In [32]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b = a
print(b)
b[1,3] = 100
print(b)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[  1   2   3   4   5]
 [  6   7   8 100  10]]
[[  1   2   3   4   5]
 [  6   7   8 100  10]]


In [33]:
a = np.array([[2,3,4,5], [11,22,33,44]])
b = a.copy()
b[1,3] = 1000
print(b)
print(a)

[[   2    3    4    5]
 [  11   22   33 1000]]
[[ 2  3  4  5]
 [11 22 33 44]]


# **Mathematical Operations**

In [34]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [35]:
# Add Values in matrix
a + 2

array([3, 4, 5, 6, 7])

In [36]:
# Subract values in matrix
a - 3

array([-2, -1,  0,  1,  2])

In [37]:
# Multiple values in matrix
a * 2

array([ 2,  4,  6,  8, 10])

In [38]:
# Take power on matrix
a ** 2

array([ 1,  4,  9, 16, 25])

In [39]:
# Divide values in matrix
a / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [40]:
# Add two matrices
b = np.array([5,6,7,8,9])
a + b

array([ 6,  8, 10, 12, 14])

In [41]:
# Cosine Value of Matrix
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [42]:
# Log value of matrix
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [43]:
# Exponentiation of matrix
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

# **Statistics**

In [44]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
# Minimum value of an array
np.min(a)

1

In [46]:
# Maximum value of an array for every row
np.max(a, axis = 1)

array([ 5, 10])

In [47]:
# Mean of an array
np.mean(a)

5.5

In [48]:
# Median of an array for each row
np.median(a, axis = 1)

array([3., 8.])

In [49]:
# Sum of an array for each column
np.sum(a, axis = 0)

array([ 7,  9, 11, 13, 15])

In [50]:
# Multiplication of two arrays with different shapes
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape)

b = np.array([[5,6], [7,8], [9,10]])
print(b)
print(b.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 5  6]
 [ 7  8]
 [ 9 10]]
(3, 2)


In [51]:
# Multply arrays using matmul
np.matmul(a, b)

array([[ 46,  52],
       [109, 124]])

In [52]:
# Multiply arrays using vectorization method using dot() method
np.dot(a, b)

array([[ 46,  52],
       [109, 124]])

# **Reorganizing Array**

In [53]:
# Reshaping the array
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
print(a.shape)

print(a.reshape(8,1))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [54]:
# Stacking the array in vertical - vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([55,66,77,88])
np.vstack([v1, v2, v2, v1])

array([[ 1,  2,  3,  4],
       [55, 66, 77, 88],
       [55, 66, 77, 88],
       [ 1,  2,  3,  4]])

In [61]:
# Horizontal Stack of arrays
h1 = np.array([[11,22,33,44], [1,2,3,4]], dtype = 'int32')
h2 = np.array([[32,43,54,65,76], [6,7,8,9,10]], dtype = 'int32')
np.hstack([h1, h2])
# h1.shape


array([[11, 22, 33, 44, 32, 43, 54, 65, 76],
       [ 1,  2,  3,  4,  6,  7,  8,  9, 10]], dtype=int32)

In [63]:
# Converting the data type using astype
a = np.array([1,2,3,4], dtype = 'float64')
a.astype('int32')

array([1, 2, 3, 4], dtype=int32)